# Generated by Django 4.2.3 on 2023-08-08 08:51

from django.db import migrations, models
import django.db.models.deletion
import places.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='ID места')),
                ('description_short', models.TextField(blank=True, null=True, verbose_name='краткое описание')),
                ('description_long', tinymce.models.HTMLField(blank=True, null=True, verbose_name='описание')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longtitude', models.FloatField(verbose_name='Долгота')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'экскурсия',
                'verbose_name_plural': 'экскурсии',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='порядковый номер')),
                ('photo', models.ImageField(upload_to=places.models.image_directory_path, verbose_name='фото')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='экскурсия')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
                'ordering': ['order'],
            },
        ),
    ]
