# Generated by Django 4.2.2 on 2023-06-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description_long', models.CharField(max_length=255, verbose_name='Описание')),
                ('description_short', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('longtitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('imgs', models.ImageField(upload_to='images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'достопримечательность',
                'verbose_name_plural': 'достопримечательности',
            },
        ),
    ]
