# Generated by Django 4.2.2 on 2023-07-07 10:51

from django.db import migrations, models
import places.models

def reorder(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    places = Place.objects.all()
    for place in places:
        for order, item in enumerate(place.images.all(), 1):
            item.order_id = order
            item.save(update_fields=['order_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order_id'], 'verbose_name': 'фото', 'verbose_name_plural': 'фото'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title'], 'verbose_name': 'экскурсия', 'verbose_name_plural': 'экскурсии'},
        ),
        migrations.AlterField(
            model_name='image',
            name='order_id',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок'),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.ImageField(upload_to=places.models.Image.image_directory_path, verbose_name='загрузка фото'),
        ),
        migrations.RunPython(reorder, reverse_code=migrations.RunPython.noop),
    ]
