# Generated by Django 4.2.2 on 2023-06-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='description_short',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
    ]
