# Generated by Django 4.2.2 on 2023-06-29 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sight',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='sight',
            old_name='description_short',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='sight',
            name='placeId',
            field=models.CharField(default=datetime.datetime(2023, 6, 29, 8, 23, 8, 507762, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='placeId'),
            preserve_default=False,
        ),
    ]
