# Generated by Django 4.2.2 on 2023-06-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_sight_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='description_long',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='description_short',
            field=models.CharField(max_length=255, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='imgs',
            field=models.URLField(verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
    ]
