# Generated by Django 4.2.2 on 2023-07-07 14:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['my_order'], 'verbose_name': 'экскурсия', 'verbose_name_plural': 'экскурсии'},
        ),
        migrations.AddField(
            model_name='place',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='описание'),
        ),
    ]
