# Generated by Django 4.2.2 on 2023-06-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_sight_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='description_short',
            field=models.TextField(verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото'),
        ),
    ]
