# Generated by Django 4.2.2 on 2023-06-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_description_long_sight_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='placeId',
            field=models.CharField(max_length=255, verbose_name='ID места'),
        ),
    ]
