# Generated by Django 4.2.2 on 2023-06-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_sight_placeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sight',
            old_name='long_description',
            new_name='description_long',
        ),
        migrations.RenameField(
            model_name='sight',
            old_name='short_description',
            new_name='description_short',
        ),
    ]
