# Generated by Django 4.2.2 on 2023-07-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_rename_long_description_sight_description_long_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sight',
            old_name='placeId',
            new_name='place_id',
        ),
    ]
